# Site
title:        Khawa Technology
tagline:      Quality Web Development
bio:          'This is the bio'
description:  "DESCRIPTION"
locale:       en_US
baseurl:      "" # the subpath of your site, e.g. /blog
url:          "" # the base hostname & protocol for your site

collections:
  posts:
    title: Articles
    output: true
  article_tags:
    title: Tags
    output: true


defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/articles/:title/"
    layout: post
    author:
- scope:
    path: ''
    type: article_tags
  values:
    permalink: "/articles/tags/:title/"
    layout: tag


# Jekyll
permalink:          /articles/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
github:             khawatechnology
bitbucket:          khawa
drupal:             khawa-technology


# personal
location:           Strasbourg, FRANCE
phone:              (+33)649676241
email:              contact@khawa.tech

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 2
paginate_path: "articles/page:num"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [assets_back, index.html_back, blog.md, 404.html, legal.md, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, docker-compose, .idea/]

t:
  en:
  fr:
